title:              EMP-NEXT
subtitle:           Sho Teramotoの記録
email:              sho-teramoto@emp-next.com
description:        Sho Teramotoの記録
author:             殿様ガエル
baseurl:            "/blog"
url:                "https://tonosama.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    tonosama
#facebook_username:  tonosama
#instagram_username:  
linkedin_username: tonosama

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
